# Generated by Django 3.1.7 on 2021-03-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_type_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': '商品类型表',
                'verbose_name_plural': '商品类型表',
                'db_table': 'tb_goodstype',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('good_pic', models.ImageField(blank=True, upload_to='static/goodspic')),
                ('good_count', models.IntegerField(blank=True)),
                ('good_desc', models.CharField(blank=True, max_length=500)),
                ('good_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goodstype')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息表',
                'db_table': 'tb_goods',
            },
        ),
    ]
